delete from book;


--Classics
INSERT INTO book VALUES ('9786589711377', '1984', 'George Orwell', 'Secker & Warburg', '1949-6-8', 'Science Fiction', '1499', '20', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/1984first.jpg/440px-1984first.jpg', '1984 is a dystopian novella by George Orwell published in 1949, which follows the life of Winston Smith, a low ranking member of the Party, who is frustrated by the omnipresent eyes of the party, and its ominous ruler Big Brother. Big Brother controls every aspect of people''s lives.');
INSERT INTO book VALUES ('9780333791035', 'The Great Gatsby', 'F. Scott Fitzgerald', 'Charles Scribner''s Sons', '1925-4-10', 'Tragedy', '799', '20', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/The_Great_Gatsby_Cover_1925_Retouched.jpg/440px-The_Great_Gatsby_Cover_1925_Retouched.jpg', 'The Great Gatsby is a 1925 novel by American writer F. Scott Fitzgerald. Set in the Jazz Age on Long Island, near New York City, the novel depicts first-person narrator Nick Carraway''s interactions with mysterious millionaire Jay Gatsby and Gatsby''s obsession to reunite with his former lover, Daisy Buchanan.');
INSERT INTO book VALUES ('9780060888695', 'To Kill a Mockingbird', 'Harper Lee', 'J. B. Lippincott & Co.', '1960-7-11', 'Southern Gothic Fiction', '1399', '12', 'https://m.media-amazon.com/images/I/51N5qVjuKAL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg', 'To Kill a Mockingbird is both a young girl''s coming-of-age story.');
INSERT INTO book VALUES ('9781428108325', 'Pride and Prejudice', 'Jane Austen', 'T. Egerton, Whitehall', '1813-1-28', 'Classic Regency Romance Novel', '599', '8', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/PrideAndPrejudiceTitlePage.jpg/220px-PrideAndPrejudiceTitlePage.jpg', 'Pride and Prejudice follows the turbulent relationship between Elizabeth Bennet, the daughter of a country gentleman, and Fitzwilliam Darcy, a rich aristocratic landowner. They must overcome the titular sins of pride and prejudice in order to fall in love and marry.');
INSERT INTO book VALUES ('9780316769532', 'The Catcher in the Rye', 'J.D. Sailinger', 'Little, Brown', '1951-7-16', 'Realistic Fiction', '1899', '69', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/The_Catcher_in_the_Rye_%281951%2C_first_edition_cover%29.jpg/220px-The_Catcher_in_the_Rye_%281951%2C_first_edition_cover%29.jpg', 'The Catcher in the Rye, novel by J.D. Salinger published in 1951. The novel details two days in the life of 16-year-old Holden Caulfield after he has been expelled from prep school. Confused and disillusioned, Holden searches for truth and rails against the “phoniness” of the adult world.');

--Harry Potter
INSERT INTO book VALUES ('9780545069670', 'Harry Potter and the Sorcerer''s Stone', 'J.K. Rowling', 'Scholastic Corporation', '1997-6-26', 'Fantasy', '1199', '25', 'https://upload.wikimedia.org/wikipedia/en/thumb/6/6b/Harry_Potter_and_the_Philosopher%27s_Stone_Book_Cover.jpg/220px-Harry_Potter_and_the_Philosopher%27s_Stone_Book_Cover.jpg', 'An orphaned boy enrolls in a school of wizardry, where he learns the truth about himself, his family and the terrible evil that haunts the magical world.');
INSERT INTO book VALUES ('9780439064866', 'Harry Potter and the Chamber of Secrets', 'J.K. Rowling', 'Scholastic Corporation', '1998-7-2', 'Fantasy', '799', '15', 'https://upload.wikimedia.org/wikipedia/en/thumb/5/5c/Harry_Potter_and_the_Chamber_of_Secrets.jpg/220px-Harry_Potter_and_the_Chamber_of_Secrets.jpg', 'The plot follows Harry''s second year at Hogwarts School of Witchcraft and Wizardry, during which a series of messages on the walls of the school''s corridors warn that the "Chamber of Secrets" has been opened and that the "heir of Slytherin" would kill all pupils who do not come from all-magical families.');
INSERT INTO book VALUES ('9780439136358', 'Harry Potter and the Prisoner of Azkaban', 'J.K. Rowling', 'Scholastic Corporation', '1999-7-8', 'Fantasy', '999', '18', 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a0/Harry_Potter_and_the_Prisoner_of_Azkaban.jpg/220px-Harry_Potter_and_the_Prisoner_of_Azkaban.jpg', 'Harry Potter & The Prisoner of Azkaban is about Harry''s 3rd year at Hogwarts. Along with friends Ron and Hermione, Harry investigates the case of Sirius Black, an escaped prisoner from Azkaban, the wizard prison.');
INSERT INTO book VALUES ('9780439139595', 'Harry Potter and the Goblet of Fire', 'J.K. Rowling', 'Scholastic Corporation', '2000-7-8', 'Fantasy', '999', '15', 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b6/Harry_Potter_and_the_Goblet_of_Fire_cover.png/220px-Harry_Potter_and_the_Goblet_of_Fire_cover.png', 'It follows Harry Potter, a wizard in his fourth year at Hogwarts School of Witchcraft and Wizardry, and the mystery surrounding the entry of Harry''s name into the Triwizard Tournament, in which he is forced to compete.');
INSERT INTO book VALUES ('9780439358064', 'Harry Potter and the Order of the Phoenix', 'J.K. Rowling', 'Scholastic Corporation', '2003-6-21', 'Fantasy', '699', '10', 'https://upload.wikimedia.org/wikipedia/en/thumb/7/70/Harry_Potter_and_the_Order_of_the_Phoenix.jpg/220px-Harry_Potter_and_the_Order_of_the_Phoenix.jpg', 'It follows Harry Potter''s struggles through his fifth year at Hogwarts School of Witchcraft and Wizardry, including the surreptitious return of the antagonist Lord Voldemort, O.W.L. exams, and an obstructive Ministry of Magic.');
INSERT INTO book VALUES ('9780439791328', 'Harry Potter and the Half-Blood Prince', 'J.K. Rowling', 'Scholastic Corporation', '2005-7-16', 'Fantasy', '899', '13', 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b5/Harry_Potter_and_the_Half-Blood_Prince_cover.png/220px-Harry_Potter_and_the_Half-Blood_Prince_cover.png', 'In this book, Harry Potter learns a lot about Lord Voldemort''s past, and Harry Potter prepares for the final battle against his nemesis with the help of Headmaster Dumbledore. But in that time, Voldemort returns to power, and makes a plan to destroy Harry.');
INSERT INTO book VALUES ('9780545010221', 'Harry Potter and the Deathly Hallows', 'J.K. Rowling', 'Scholastic Corporation', '2007-7-21', 'Fantasy', '1399', '24', 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a9/Harry_Potter_and_the_Deathly_Hallows.jpg/220px-Harry_Potter_and_the_Deathly_Hallows.jpg', 'The Deathly Hallows is about Harry Potter and his friends finding ways to destroy Voldemort. They learn that even good contains a bit of evil, and vise versa. Even though the trio faces many difficulties, they persevere.');

--Diary of a Wimpy Kid
INSERT INTO book VALUES ('9781439582633', 'Diary of a Wimpy Kid', 'Jeff Kinney', 'Paw Prints', '2007-4-1', 'Realistic Fiction', '1099', '13', 'https://m.media-amazon.com/images/I/51VOl-w93UL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg', 'Greg Heffley is a normal American kid, albeit one with a habit of getting into (and out of) trouble. His diary, complete with hilarious cartoons, records a year in his life and follows his relationships with his nerdy best friend Rowley, annoying brothers Roderick and Manny and long-suffering parents.');
INSERT INTO book VALUES ('9781419741869', 'Diary of a Wimpy Kid: Rodrick Rules', 'Jeff Kinney', 'Harry N. Abrams', '2008-2-1', 'Realistic Fiction', '999', '10', 'https://m.media-amazon.com/images/I/51UuA+sIzGL._SX333_BO1,204,203,200_.jpg', 'Diary of a Wimpy Kid: Rodrick Rules chronicles Greg''s attempts to navigate the hazards of middle school, impress the girls, steer clear of the school talent show, and most important, keep his secret safe.');
INSERT INTO book VALUES ('9781419741876', 'Diary of a Wimpy Kid: The Last Straw', 'Jeff Kinney', 'Harry N. Abrams', '2009-1-13', 'Realistic Fiction', '999', '10', 'https://m.media-amazon.com/images/I/51ZosjyojoL._SX333_BO1,204,203,200_.jpg', 'The last straw is an incident at church on Easter, where Greg accidentally sits on his spoiled little brother Manny''s chocolate bunny and stains the back of his pants with chocolate.');
INSERT INTO book VALUES ('9781419741883', 'Diary of a Wimpy Kid: Dog Days', 'Jeff Kinney', 'Amulet Books', '2009-10-12', 'Realistic Fiction', '999', '10', 'https://m.media-amazon.com/images/I/51aIEFQlQ+L._SX333_BO1,204,203,200_.jpg', 'Dog Days is about Greg Heffley, the main protagonist, having his summer plans ruined when his parents leave him home with his mean older brother for the summer');
INSERT INTO book VALUES ('9781419741890', 'Diary of a Wimpy Kid: The Ugly Truth', 'Jeff Kinney', 'Harry N. Abrams', '2010-10-21', 'Realistic Fiction', '899', '8', 'https://m.media-amazon.com/images/I/51OqgiOTXYL._SX333_BO1,204,203,200_.jpg', 'Greg Heffley has always been in a hurry to grow up. But is getting older really all it''s cracked up to be? Greg suddenly finds himself dealing with the pressures of boy-girl parties, increased responsibilities, and even the awkward changes that come with getting older—all without his best friend, Rowley, at his side.');
INSERT INTO book VALUES ('9781419741913', 'Diary of a Wimpy Kid: Cabin Fever', 'Jeff Kinney', 'Harry N. Abrams', '2011-11-1', 'Realistic Fiction', '1199', '11', 'https://m.media-amazon.com/images/I/513pdNF+IHL._SX333_BO1,204,203,200_.jpg', 'Cabin Fever follows the misadventures of Greg Heffley as his attempt to earn money for Christmas gifts gets him in trouble at school just as a massive blizzard sets in.');
INSERT INTO book VALUES ('9781419741937', 'Diary of a Wimpy Kid: The Third Wheel', 'Jeff Kinney', 'Harry N. Abrams', '2012-11-13', 'Realistic Fiction', '999', '9', 'https://m.media-amazon.com/images/I/51BTXclnFbL._SX333_BO1,204,203,200_.jpg', 'A Valentine''s Day dance at Greg''s school has turned his world upside down. As Greg scrambles to find a date, he''s worried he''ll be left out in the cold on the big night. His bestfriend, Rowley, doesn''t have any prospects either but that''s small consolation.');
INSERT INTO book VALUES ('9781419741944', 'Diary of a Wimpy Kid: Hard Luck', 'Jeff Kinney', 'Harry N. Abrams', '2013-11-1', 'Realistic Fiction', '1199', '9', 'https://m.media-amazon.com/images/I/51oFXKuPVlL._SX333_BO1,204,203,200_.jpg', 'In this book, Greg''s best friend Rowley ditches him, and Greg struggles to make new friends. On Easter, he finds a Magic 8-Ball and attempts to change his luck by using it to make decisions for him.');
INSERT INTO book VALUES ('9781419741951', 'Diary of a Wimpy Kid: The Long Haul', 'Jeff Kinney', 'Harry N. Abrams', '2014-11-4', 'Realistic Fiction', '1099', '7', 'https://m.media-amazon.com/images/I/51IMI7XisSL._SX333_BO1,204,203,200_.jpg', 'The journey starts off full of promise, then quickly takes several wrong turns. Gas station bathrooms, crazed seagulls, a fender bender, and a runaway pig—not exactly Greg Heffley''s idea of a good time. But even the worst road trip can turn into an adventure—and this is one the Heffleys won''t soon forget.');
INSERT INTO book VALUES ('9781419741968', 'Diary of a Wimpy Kid: Old School', 'Jeff Kinney', 'Harry N. Abrams', '2015-11-1', 'Realistic Fiction', '1499', '5', 'https://m.media-amazon.com/images/I/51Z0YPtMckL._SX333_BO1,204,203,200_.jpg', 'That''s the question Greg Heffley is asking as his town voluntarily unplugs and goes electronics-free. But modern life has its conveniences, and Greg isn''t cut out for an old-fashioned world. With tension building inside and outside the Heffley home, will Greg find a way to survive? Or is going “old school” just too hard for a kid like Greg?');
INSERT INTO book VALUES ('9781419741975', 'Diary of a Wimpy Kid: Double Down', 'Jeff Kinney', 'Harry N. Abrams', '2016-11-1', 'Realistic Fiction', '1499', '3', 'https://m.media-amazon.com/images/I/51+oSG2gzhL._SX339_BO1,204,203,200_.jpg', 'When Greg finds an old video camera in his basement, he thinks he may have discovered just the thing to prove he''s got big-time talent. With the help of his best friend, Rowley, Greg hatches a plan to make a scary movie . . . and to become rich and famous in the process. But is doubling down on movie-making a smart plan? Or is it just a recipe for doubling Greg''s troubles?');
INSERT INTO book VALUES ('9781419741982', 'Diary of a Wimpy Kid: The Getaway', 'Jeff Kinney', 'Harry N. Abrams', '2017-11-27', 'Realistic Fiction', '1499', '3', 'https://m.media-amazon.com/images/I/51rK1qn2VDL._SX339_BO1,204,203,200_.jpg', 'With the cold weather and the stress of the approaching holiday season, the Heffleys decide to escape to a tropical island resort for some much-needed rest and relaxation. A few days in paradise should do wonders for Greg and his frazzled family.');
INSERT INTO book VALUES ('9781419741999', 'Diary of a Wimpy Kid: The Meltdown', 'Jeff Kinney', 'Harry N. Abrams', '2018-10-30', 'Realistic Fiction', '1499', '3', 'https://m.media-amazon.com/images/I/51vAe1HvgVL._SX339_BO1,204,203,200_.jpg', 'When snow shuts down Greg Heffley''s middle school, his neighborhood transforms into a wintry battlefield. Rival groups fight over territory, build massive snow forts, and stage epic snowball fights. And in the crosshairs are Greg and his trusty best friend, Rowley Jefferson.');
INSERT INTO book VALUES ('9781419739033', 'Diary of a Wimpy Kid: Wrecking Ball', 'Jeff Kineey', 'Harry N. Abrams', '2019-11-1', 'Realistic Fiction', '1499', '3', 'https://m.media-amazon.com/images/I/51381p7x0vL._SX338_BO1,204,203,200_.jpg', 'Once the walls come down, all sorts of problems start to crop up. Rotten wood, toxic mold, unwelcome critters, and something even more sinister all make Greg and his family wonder if the renovations are worth the trouble.');
INSERT INTO book VALUES ('9781419748684', 'Diary of a Wimpy Kid: The Deep End', 'Jeff Kinney', 'Harry N. Abrams', '2020-10-27', 'Realistic Fiction', '1499', '3', 'https://m.media-amazon.com/images/I/51R4+SrZu6L._SX339_BO1,204,203,200_.jpg', ' Greg Heffley and his family hit the road for a cross-country camping trip, ready for the adventure of a lifetime. But things take an unexpected turn, and they find themselves stranded at an RV park that''s not exactly a summertime paradise. When the skies open up and the water starts to rise, the Heffleys wonder if they can save their vacation—or if they''re already in too deep.');
INSERT INTO book VALUES ('9781419749155', 'Diary of a Wimpy Kid: Big Shot', 'Jeff Kinney', 'Harry N. Abrams', '2021-10-26', 'Realistic Fiction', '1499', '3', 'https://m.media-amazon.com/images/I/51U-z4zRa5L._SX338_BO1,204,203,200_.jpg', 'After a disastrous field day competition at school, Greg decides that when it comes to his athletic career, he''s officially retired. But after his mom urges him to give sports one more chance, he reluctantly agrees to sign up for basketball.');
INSERT INTO book VALUES ('9781419762949', 'Diary of a Wimpy Kid: Diper Overlode', 'Jeff Kinney', 'Harry N. Abrams', '2022-10-25', 'Realistic Fiction', '1499', '3', 'https://m.media-amazon.com/images/I/519lZ0f+kUL._SX339_BO1,204,203,200_.jpg', 'When he decides to tag along with his brother Rodrick''s band, Löded Diper, Greg doesn''t realize what he''s getting into. But he soon learns that late nights, unpaid gigs, fighting between band members, and money troubles are all part of the rock ''n'' roll lifestyle.');

--Game of Thrones
INSERT INTO book VALUES ('9780007459483', 'A Game of Thrones', 'George R.R. Martin', 'Bantam Spectra', '1996-8-1', 'Fantasy', '2499', '8', 'https://upload.wikimedia.org/wikipedia/en/thumb/9/93/AGameOfThrones.jpg/220px-AGameOfThrones.jpg', 'A Game of Thrones, is the first in an epic series about a land in which the seasons shift between periods of seemingly endless summer and seemingly endless winter. The story begins with the kingdom of Winterfell facing both external and internal dangers.');
INSERT INTO book VALUES ('9780006479895', 'A Clash of Kings', 'George R.R. Martin', 'Bantam Spectra', '1998-11-16', 'Fantasy', '3999', '12', 'https://upload.wikimedia.org/wikipedia/en/3/39/AClashOfKings.jpg', 'A Clash of Kings depicts the Seven Kingdoms of Westeros in civil war, while the Night''s Watch mounts a reconnaissance to investigate the mysterious people known as wildlings. Meanwhile, Daenerys Targaryen continues her plan to conquer the Seven Kingdoms.');
INSERT INTO book VALUES ('9780553106633', 'A Storm of Swords', 'George R.R. Martin', 'Bantam Spectra', '2000-8-8', 'Fantasy', '2299', '5', 'https://upload.wikimedia.org/wikipedia/en/thumb/2/24/AStormOfSwords.jpg/220px-AStormOfSwords.jpg', 'A Storm of Swords continues the story where A Clash of Kings ended. The novel describes the increasingly vicious War of Five Kings in Westeros, Daenerys''s strengthening forces in the East, and the oncoming threat of the Others, a ghostly army that is nearly invincible.');
INSERT INTO book VALUES ('9780553801507', 'A Feast for Crows', 'George R.R. Martin', 'Bantam Spectra', '2005-10-17', 'Fantasy', '1699', '4', 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a3/AFeastForCrows.jpg/220px-AFeastForCrows.jpg', 'A Feast for Crows focuses on the Lannister family''s continuing consolidation of power following victory in the “War of the Five Kings.” Specifically, it follows the events precipitated by the murder of Tywin Lannister, who had been de facto ruler of Westeros. In his place, his daughter Cersei, seizes power.');
INSERT INTO book VALUES ('9780553801477', 'A Dance with Dragons', 'George R.R. Martin', 'Bantam Spectra', '2011-7-12', 'Fantasy', '1799', '6', 'https://upload.wikimedia.org/wikipedia/en/thumb/5/5d/A_Dance_With_Dragons_US.jpg/220px-A_Dance_With_Dragons_US.jpg', 'In the aftermath of a colossal battle, the future of the Seven Kingdoms hangs in the balance—beset by newly emerging threats from every direction. In the east, Daenerys Targaryen, the last scion of House Targaryen, rules with her three dragons as queen of a city built on dust and death.');
INSERT INTO book VALUES ('9781524796280', 'Fire & Blood', 'George R.R. Martin', 'Bantam Spectra', '2018-11-20', 'Fantasy', '1699', '8', 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c2/Fire_%26_Blood_%282018%29_hardcover.jpg/220px-Fire_%26_Blood_%282018%29_hardcover.jpg', 'Fire & Blood tells the history of House Targaryen, the dynasty that ruled the Seven Kingdoms of Westeros in the backstory of his series A Song of Ice and Fire.');