delete from book;
delete from review;

INSERT INTO book VALUES ('9786589711377', '1984', 'George Orwell', 'Secker & Warburg', '1949-6-8', 'Science Fiction', '1499', '10', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/1984first.jpg/440px-1984first.jpg', '1984 is a dystopian novella by George Orwell published in 1949, which follows the life of Winston Smith, a low ranking member of the Party, who is frustrated by the omnipresent eyes of the party, and its ominous ruler Big Brother. Big Brother controls every aspect of people''s lives.');
INSERT INTO book VALUES ('9786589711378', '1984', 'George Orwell 2', 'Secker & Warburg', '1949-6-8', 'Science Fiction', '1499', '10', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/1984first.jpg/440px-1984first.jpg', '1984 is a dystopian novella by George Orwell published in 1949, which follows the life of Winston Smith, a low ranking member of the Party, who is frustrated by the omnipresent eyes of the party, and its ominous ruler Big Brother. Big Brother controls every aspect of people''s lives.');
INSERT INTO book VALUES ('9786589711399', '1984', 'George Orwell 2', 'Secker & Warburg', '1949-6-8', 'Science Fiction', '1499', '10', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/1984first.jpg/440px-1984first.jpg', '1984 is a dystopian novella by George Orwell published in 1949, which follows the life of Winston Smith, a low ranking member of the Party, who is frustrated by the omnipresent eyes of the party, and its ominous ruler Big Brother. Big Brother controls every aspect of people''s lives.');
INSERT INTO book VALUES ('9780333791035', 'The Great Gatsby', 'F. Scott Fitzgerald', 'Charles Scribner''s Sons', '1925-4-10', 'Tragedy', '799', '20', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/The_Great_Gatsby_Cover_1925_Retouched.jpg/440px-The_Great_Gatsby_Cover_1925_Retouched.jpg', 'The Great Gatsby is a 1925 novel by American writer F. Scott Fitzgerald. Set in the Jazz Age on Long Island, near New York City, the novel depicts first-person narrator Nick Carraway''s interactions with mysterious millionaire Jay Gatsby and Gatsby''s obsession to reunite with his former lover, Daisy Buchanan.');

INSERT INTO review (review, ISBN, username)
VALUES ('Mary', '9786589711377', 'How can I love a story so much as it destroys my soul? This book leads you down a dark hole and you won''t recover when you make the journey. Yet, you have to make the journey… you must see the destination. When you do, you realize humanity is doomed but… you still love the story.');
INSERT INTO review (review, ISBN, username)
VALUES ('9786589711377', 'Billy from Middle School', 'Too long.');
INSERT INTO review (review, ISBN, username)
VALUES ('9780333791035', 'Richard', 'It is one of those reads you can''t put down. The writer is colorful and descriptive. He makes you feel like you are almost there. Definitely a good read.');